#
# HOLOCRON CONFIGURATION FILE.
#

sitename:    kalnitsky's way
siteurl:     http://kalnitsky.org
author:      Igor Kalnitsky


paths:
   content: {here}
   output:  {here}/_build
   theme:   {here}/_theme


theme:
   navigation: !!pairs
      - about:      /about/
      - projects:   /projects/
      - feed:       /feed.xml

   counters:
      google_analytics: UA-56182606-1


generators:
   enabled: [sitemap, index, feed]
