#
# HOLOCRON CONFIGURATION FILE.
#

site:
  title:    kalnitsky's way
  author:   Igor Kalnitsky
  url:      http://kalnitsky.org


paths:
  content: {here}
  output:  {here}/_build


theme:
  navigation: !!pairs
    - about:      /about/
    - projects:   /projects/
    - talks:      /talks/
    - feed:       /feed.xml

  ribbon:
    text:     Star On GitHub
    link:     https://github.com/ikalnitsky/kalnitsky.org

  copyright: >
    &copy; 2014,
    <a rel="me" href="/about/">Igor Kalnitsky</a><br>

  counters:
    google_analytics: UA-56182606-1

  twitter_cards:
     username: ikalnitsky
