#
# HOLOCRON CONFIGURATION FILE.
#

site:
  title:    Ihor Kalnytskyi
  author:   Ihor Kalnytskyi
  url:      https://kalnytskyi.com

paths:
  content: {here}
  output:  {here}/_site

theme:
  sidebar:
    photo: /about/me.jpg
    about: |
      <a href="/about" rel="me">Ihor Kalnytshyi</a>'s thoughts & writings

  navigation: !!pairs
    - Archive:   /
    - How To:    /howto/
    - Talks:     /talks/
    - Feed:      /feed.xml

  copyright: <a rel="me" href="/about/">Ihor Kalnytskyi</a>

  counters:
    google_analytics: UA-91466040-1

  twitter_cards:
     username: ikalnytskyi

processors:
  - name: source
    when:
      - operator: match
        attribute: source
        pattern: '[^_.].*$'

  - name: metadata
    metadata:
      template: page.j2
    when:
      - operator: match
        attribute: source
        pattern: '.*\.(md|markdown)$'

      - operator: match
        attribute: source
        pattern: '^(?!talks\/[^\/]+\/.*)'

  - name: frontmatter
    when:
      - operator: match
        attribute: source
        pattern: '.*\.(md|markdown)$'

      - operator: match
        attribute: source
        pattern: '^(?!talks\/[^\/]+\/.*)'

  - name: markdown
    when:
      - operator: match
        attribute: source
        pattern: '.*\.(md|markdown)$'

      - operator: match
        attribute: source
        pattern: '^(?!talks\/[^\/]+\/.*)'

  - name: atom
    save_as: feed.xml
    when:
      - operator: match
        attribute: source
        pattern: '\d{{2,4}}/\d{{1,2}}/\d{{1,2}}.*\.(md|markdown)$'

  - name: index
    when:
      - operator: match
        attribute: source
        pattern: '\d{{2,4}}/\d{{1,2}}/\d{{1,2}}.*\.(md|markdown)$'

  - name: sitemap
    when:
      - operator: match
        attribute: source
        pattern: '.*\.(md|markdown)$'

      - operator: match
        attribute: source
        pattern: '^(?!talks\/[^\/]+\/.*)'

  - name: commit
    path: _site

ext:
  enabled:
    - user-theme
