#
# HOLOCRON CONFIGURATION FILE.
#

site:
  title:    Ihor Kalnytskyi
  author:   Ihor Kalnytskyi
  url:      https://kalnytskyi.com

paths:
  content: {here}
  output:  {here}/_build

theme:
  sidebar:
    photo: /me.jpg
    about: |
      <a href="/about" rel="me">Ihor Kalnytshyi</a>'s thoughts & writings

  navigation: !!pairs
    - Archive:   /
    - Projects:  /projects/
    - Talks:     /talks/
    - Feed:      /feed.xml

  copyright: <a rel="me" href="/about/">Ihor Kalnytskyi</a>

  counters:
    google_analytics: UA-91466040-1

  twitter_cards:
     username: ikalnytskyi

ext:
  enabled:
    - markdown
    - index
    - feed
    - sitemap
    - user-theme
