#
# HOLOCRON CONFIGURATION FILE.
#

site:
  title:    kalnytskyi's way
  author:   Ihor Kalnytskyi
  url:      https://kalnytskyi.com


paths:
  content: {here}
  output:  {here}/_build


theme:
  navigation: !!pairs
    - about:      /about/
    - projects:   /projects/
    - talks:      /talks/
    - feed:       /feed.xml

  ribbon:
    text:     Star On GitHub
    link:     https://github.com/ikalnytskyi/kalnitsky.org

  copyright: >
    &copy; 2014,
    <a rel="me" href="/about/">Ihor Kalnytskyi</a><br>

  counters:
    google_analytics: UA-91466040-1

  twitter_cards:
     username: ikalnytskyi
