# At some point there were blog poses from 2010, 2011 and 2012. They are not
# here, they are archived and hence we need to set proper redirects.

[[redirects]]
from = "/2010/*"
to = "http://archive.kalnytskyi.com/2010/:splat"

[[redirects]]
from = "/2011/*"
to = "http://archive.kalnytskyi.com/2011/:splat"

[[redirects]]
from = "/2012/*"
to = "http://archive.kalnytskyi.com/2012/:splat"
